### ISSUE TITLE
[S1-PB10]  Membuat halaman profil

### ISSUE THREAD

**Issue by ysb777** [gumballs17/SI4402-KEL4#13]
Membuat halaman profile untuk user dan budayawan

**Comment by ysb777** [comment]
![Image](https://user-images.githubusercontent.com/82760257/227411177-345705b2-2360-4b4d-8397-4419f8d35ef0.jpg)

**Comment by vadelaristi** [comment]
Halaman Profile

![Image](https://user-images.githubusercontent.com/115638050/227414653-12249072-2f3f-4982-967a-7d623df3ca61.png)

**Comment by vadelaristi** [comment]
![Image](https://user-images.githubusercontent.com/115638050/227414727-4e0627de-f646-430a-a562-1a5a3b950c15.png)
